name: PR Unit Tests

on: 
  pull_request:
    branches: [ "*" ]
  repository_dispatch:
    types: [pr-event]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Set up Node.js (or your required runtime)
      uses: actions/setup-node@v2
      with:
        node-version: '14' # specify your Node.js version

    - name: Install dependencies
      run: npm install

    - name: Run unit tests
      run: npm test
